# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  solutionPath: '.'
  appProjectPath: 'MoviesSite.App'

steps:
- script: dotnet build "$(solutionPath)" --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: '$(appProjectPath)'
    publishWebProjects: false
    arguments: >-
      --configuration $(buildConfiguration)
      --output $(System.DefaultWorkingDirectory)/publish
    zipAfterPublish: true
  displayName: dotnet publish
- task: AzureRmWebAppDeployment@4
  inputs:
    # based on name given to Azure Resource Manager service connection
    azureSubscription: 'nick-azure'
    # the name of the App Service resource in Azure (also, the subdomain of the .azurewebsites URL)
    WebAppName: 'escalona1902movies'
    Package: $(System.DefaultWorkingDirectory)/publish/*.zip
